CREATE DATABASE IF NOT EXISTS HASTANE_OTOMASYON_DB;
USE HASTANE_OTOMASYON_DB;

CREATE TABLE IF NOT EXISTS KULLANICI(
	kullaniciId INT PRIMARY KEY AUTO_INCREMENT,

    kullaniciAd VARCHAR(40) NOT NULL,
    kullaniciSoyad VARCHAR(40) NOT NULL,
    kullaniciDogTar DATE NOT NULL,
    kullaniciTelNo CHAR(11) NOT NULL,

    kullaniciSehir VARCHAR(25) NOT NULL,
    kullaniciIlce VARCHAR(40) NOT NULL,

    kullaniciKilo TINYINT,
    kullaniciBoy TINYINT,
    kullaniciCinsiyet ENUM('E','K'),
	kullaniciKanGrubu ENUM('AB RH+','AB RH-','A RH+','A RH-','0 RH+','0 RH-')
);
SHOW TABLES;
DESCRIBE KULLANICI;
-- ALTER TABLE KULLANICI
-- MODIFY COLUMN kullaniciDogTar DATE NOT NULL;


CREATE TABLE IF NOT EXISTS KURULUS(
	kurulusId INT PRIMARY KEY AUTO_INCREMENT,

    kurulusAd VARCHAR(80) NOT NULL,
    kurulusSehir VARCHAR(40) NOT NULL,
    kurulusIlce VARCHAR(40) NOT NULL,
    kurulusTar DATE NOT NULL,
    kurulusTur ENUM('BIRINCI_BASAMAK','IKINCI_BASAMAK','UCUNCU_BASAMAK') NOT NULL,
    kurulusSorumlusu VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS SAGPERSONEL( -- SAGPERSONEL(1):KURULUS(1)
	sagPersId INT PRIMARY KEY AUTO_INCREMENT,
    sagPersAd VARCHAR(40) NOT NULL,
    sagPersSoyad VARCHAR(40) NOT NULL,
    sagPersBirim VARCHAR(40) NOT NULL,

    kurulusId INT UNIQUE,
    FOREIGN KEY (kurulusId) REFERENCES KURULUS(kurulusId) -- 1:1 ILISKI
    ON DELETE SET NULL -- BAGLI OLUNAN KURULUS SILINIRSE SAGPERSONEL'DE BU KOLONU NULL YAP
);
-- DROP TABLE SAGPERSONEL;

CREATE TABLE IF NOT EXISTS RANDEVU(
	randevuId INT PRIMARY KEY AUTO_INCREMENT,

    randevuTar DATETIME NOT NULL,
    kullaniciId INT,
    sagPersId INT,

    FOREIGN KEY (kullaniciId) REFERENCES KULLANICI(kullaniciId)
    ON DELETE CASCADE, -- KULLANICI BILGISININ SILINMESI GEREKIRSE ONA BAGLI RANDEVULARI SIL

    FOREIGN KEY (sagPersId) REFERENCES SAGPERSONEL(sagPersId)
    ON DELETE CASCADE -- SAGPERSONEL'DE KAYIT SILINMESI GEREKIRSE ONA BAGLI RANDEVULARI SIL
);

CREATE TABLE IF NOT EXISTS RECETE_TUR(
	receteTurId INT PRIMARY KEY AUTO_INCREMENT,
    receteTurAd VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS RECETE(
	receteId INT PRIMARY KEY AUTO_INCREMENT,

    receteKod VARCHAR(50) NOT NULL,
    receteTar TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    receteAlinmaTar DATETIME,

    receteTurId INT,
    kullaniciId INT,
    sagPersId INT,

    FOREIGN KEY (receteTurId) REFERENCES RECETE_TUR(receteTurId),

    FOREIGN KEY (kullaniciId) REFERENCES KULLANICI(kullaniciId)
    ON DELETE CASCADE,

    FOREIGN KEY (sagPersId) REFERENCES SAGPERSONEL(sagPersId)
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ENVANTER(
	envanterId INT PRIMARY KEY AUTO_INCREMENT,

    doktorKapasite SMALLINT UNSIGNED NOT NULL,
    hemsireKapasite SMALLINT UNSIGNED NOT NULL,
    yardimciSagKapasite SMALLINT UNSIGNED NOT NULL,

    yatakKapasite SMALLINT UNSIGNED NOT NULL,
    ambulansSay SMALLINT UNSIGNED NOT NULL,

    kurulusId INT UNIQUE, -- 1:1
    FOREIGN KEY (kurulusId) REFERENCES KURULUS(kurulusId)
    ON DELETE RESTRICT -- BURADAKI KAYITLAR SILINMEDEN SILMEYE IZIN VERMEZ
);
